Remove the migrations.

diff --git a/.github/workflows/behat.yml b/.github/workflows/behat.yml
--- a/.github/workflows/behat.yml
+++ b/.github/workflows/behat.yml
@@ -64,13 +64,13 @@ jobs:
       - name: Create metadata directory
         run: mkdir -p config/serializer/v1
 
-      - name: Run Migration
-        run: |
-          composer require --dev symfony/orm-pack
-          php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
-          php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
-        env:
-          DATABASE_URL: mysql://root:secret@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/greatfoods?serverVersion=8.0
+      # - name: Run Migration
+      #   run: |
+      #     composer require --dev symfony/orm-pack
+      #     php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
+      #     php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+      #   env:
+      #     DATABASE_URL: mysql://root:secret@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/greatfoods?serverVersion=8.0
       
       - name: Run behat tests
         run: ./vendor/bin/behat
